### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by smk291** [mtcrouse/q2-project#10]
Sidenote: favorites route handlers are fucked and worthless.

1. Frontend

- [ ] Login page (Sign up alongside?) (backend)
- [ ] Profile page (backend) - favorites
- [ ] Lists (Most favorited; recent favorites; 
- [ ] Frequent/popular searches should be displayed in search box
- [ ] Get trending hashtags and topics
- [ ] http://greensock.com/gsap

1a. Display of search results and tweets

- [ ] Search results - tweets (left)
- [ ] Stream - running list of tweets if retweets above a certain number. (stretch)
- [ ] Media
- [ ] Links

Metta:
- Search box functionality
- Displaying search results for keyword searches

Sam:
- (explore animations)
- Profile page
- [ ] Get lists (favorites, searches) and display -- from DB
- [ ] Create account from webpage

Mess around.

Backend:
- [ ] Create account from webpage
- [ ] Get user info from db and put on page
- [ ] Get lists (favorites, searches) and display -- from DB
- [ ] Get lists (media, links) and display -- from tweets stream or search
